package importer

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/notshekhar/drover/internal/object"
)

// document is the envelope every generated object is written in.
type document struct {
	APIVersion string      `yaml:"apiVersion"`
	Kind       object.Kind `yaml:"kind"`
	Metadata   struct {
		Name   string            `yaml:"name"`
		Labels map[string]string `yaml:"labels,omitempty"`
	} `yaml:"metadata"`
	Spec any `yaml:"spec"`
}

// marshal writes one document with two-space indentation, which is what the
// rest of drover's yaml looks like and what someone will diff this against.
func marshal(d *document) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(d); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func requestDocument(name string, spec *object.HTTPRequestSpec) ([]byte, error) {
	d := &document{APIVersion: object.APIVersion, Kind: object.KindHTTPRequest, Spec: spec}
	d.Metadata.Name = name
	return marshal(d)
}

// environmentDocument carries the base url every generated request points at.
//
// It is emitted even when the spec named no server, with a placeholder,
// because a request whose {{baseUrl}} resolves to nothing fails at call time
// with a confusing error -- and an obviously-fake url in a file someone is
// about to read is the clearer failure.
func environmentDocument(name, serverURL string) ([]byte, error) {
	if serverURL == "" {
		serverURL = "https://example.invalid  # the spec named no server; fill this in"
	}
	d := &document{APIVersion: object.APIVersion, Kind: object.KindEnvironment}
	d.Metadata.Name = name
	d.Spec = map[string]any{"variables": map[string]string{"baseUrl": serverURL}}
	out, err := marshal(d)
	if err != nil {
		return nil, err
	}
	head := fmt.Sprintf("# generated by drover import -- edit freely, this is an ordinary document\n")
	return append([]byte(head), out...), nil
}
